### ISSUE TITLE
problemframecontext  function

### ISSUE THREAD

**Issue by xcww-bin** [Neil-Shah/GANs-for-Speech-Enhancement#1]
hello,could you tell me what's the  framecontext function in Feature_extraction_training.m. It seems not to be in Matlab or in your file. Thankyou very much

**Comment by czh-learn** [comment]
I meet the same problem that can not find function of framecontext,  does someone solve it ? thanks

**Comment by Neil-Shah** [comment]
Have updated the framexontext code in the repository
